{
  "formatVersion": "1.1",
  "component": {
    "group": "be.kuleuven",
    "module": "CheckNeigboursInGrid",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CheckNeigboursInGrid-1.0.jar",
          "url": "CheckNeigboursInGrid-1.0.jar",
          "size": 2290,
          "sha512": "0a8d4b88802d3c50863ca61dc063e377331897913f5fd3f9971acb170692d63715f010bd1506513dc3f0587bc4657e168762f8d6bdb45c6f657d4f9ef736ca7f",
          "sha256": "47714080c48eaecec359b600afbcd9f76ee421a84331b20a570b5b252e9a2feb",
          "sha1": "49e049ec836e5089a9a6fdef945657dffb6e6c74",
          "md5": "f569faeeaa277d2c5eb7520d5ff7cc83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CheckNeigboursInGrid-1.0.jar",
          "url": "CheckNeigboursInGrid-1.0.jar",
          "size": 2290,
          "sha512": "0a8d4b88802d3c50863ca61dc063e377331897913f5fd3f9971acb170692d63715f010bd1506513dc3f0587bc4657e168762f8d6bdb45c6f657d4f9ef736ca7f",
          "sha256": "47714080c48eaecec359b600afbcd9f76ee421a84331b20a570b5b252e9a2feb",
          "sha1": "49e049ec836e5089a9a6fdef945657dffb6e6c74",
          "md5": "f569faeeaa277d2c5eb7520d5ff7cc83"
        }
      ]
    }
  ]
}
